### ISSUE TITLE
Add workflow that runs the examples

### ISSUE THREAD

**Issue by tms-bananaquit** [mitre/menelaus#8]
If these are in the form of notebooks --  example using nbconvert: https://github.com/AureumChaos/LEAP/blob/master/tests/jupyter/test_jupyter.py
- Annotate the jupyter/example tests with `@pytest.mark.no_cover` so system tests aren't included in the coverage report.

**Comment by tms-bananaquit** [comment]
This is another one that should probably use `pip install -e .[test]` instead of `[dev]`.

**Comment by Anmol-Srivastava** [comment]
A Python example-script-runner is added among the unit tests, but the example scripts create a lot of output are not always needed:

- [ ] when run by the unit test script, examples should not create output (use `test_env_var`)
- [ ] add unit test script for Jupyter notebooks
- [ ] since `examples.yml` runs only example scripts, unit tests should be reorganized so that the main workflow only runs the non-example test files -- maybe using more directories for labelling, etc.
